# Project information
site_name: tslib documentation
site_url: https://jacgoldsm.github.io/tslib
site_description: >-
  Complete and consistent API for leads, lags, and differences with Pandas

# Repository
repo_name: "jacgoldsm/tslib"
repo_url: "https://github.com/jacgoldsm/tslib"

# Configuration
docs_dir: docs/
watch:
  - tslib/

theme:
  name: "material"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: "blue grey"
      accent: "light blue"
  icon:
    logo: "fontawesome/solid/book"
  features:
    - navigation.instant
    # - navigation.tabs
    - navigation.top
    - toc.follow
    - content.code.copy
  language: en

# Page tree
# We customize the navigation by hand to control the order
# in which pages show up.
nav:
  - Home: index.md
  - API Reference:
      - Pandas: api/pandas.md
      # - PySpark: api/pyspark.md  # will be added later
  - Development Guide: devguide.md
  - Changelog: CHANGELOG.md
  - Authors: AUTHORS.md

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: "google"
            docstring_options:
              trim_doctest_flags: true
            show_root_toc_entry: false
            show_submodules: true
            show_source: true
# - mknotebooks:
#     execute: true
#     write_markdown: true
#     allow_errors: true
#     timeout: 1200
#     binder: true
#     binder_service_name: "gh"
#     binder_branch: "master"

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
  # - pymdownx.tabbed:
  #     alternate_style: true
  - pymdownx.superfences

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra_css:
  - css/apidocs.css